route:
  receiver: 'gitlab-alerts'
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  group_by: [alertname]

receivers:
- name: 'gitlab-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:80/alerts'
    send_resolved: true