version: '3'

services:
  prometheus-server:
    image: prom/prometheus:v2.3.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-server.yml:/etc/prometheus/prometheus.yml
      - ./node-exporter-rules.yml:/etc/prometheus/node-exporter-rules.yml
    
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    
  alertmanager:
    image: prom/alertmanager:v0.15.2
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:30080'
        gitlab_rails['gitlab_shell_ssh_port']=30022;
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '30080:30080'
      # - '443:443'
      - '30022:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'