groups:
- name: node-exporter
  rules:
  - alert: BootTimeTooHigh
    expr: node_boot_time_seconds > 0
    for: 1s
    labels:
      severity: fatal
    annotations:
      summary: "Boot time took too long on {{ $labels.instance }}"
      description: "{{ $labels.instance }} had a boot time of (current value: {{ $value }}s).  This is unacceptable :P"